### ISSUE TITLE
Format all C++ code in this repo.

### ISSUE THREAD

**Issue by usx95** [usx95/general-coding-usaxena95#6]
You can use clang-format to format the c++ code.

**Comment by planetplut0** [comment]
Hey can you assign it to me ?

**Comment by pshyticyash** [comment]
please assign it to me

**Comment by usx95** [comment]
@pshyticyash 
Feel free to submit a PR.  [Keep it small]

**Comment by abhishekrawe** [comment]
i want to work on it
