### ISSUE TITLE
Rename files to snake case. Add cpp extension to each file.

### ISSUE THREAD

**Issue by usx95** [usx95/general-coding-usaxena95#7]
Try to follow Google C++ style guide.
Ref: https://google.github.io/styleguide/cppguide.html

**Comment by sonuishaq67** [comment]
Hey @usx95  I think I can do this !

**Comment by usx95** [comment]
@sonuishaq67 
Feel free to contribute. [Keep the PR small]

**Comment by sonuishaq67** [comment]
I think #10 does it right ?
Is there anything wrong with #10 ?

**Comment by usx95** [comment]
@sonuishaq67 it fixes one file.

**Comment by sonuishaq67** [comment]
Okay will be doing the rest

**Comment by sonuishaq67** [comment]
Hey @usx95 I implemented this in #14
